/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AdminDevelopersRouteImport } from './routes/admin.developers'
import { Route as AdminReconciliationRouteImport } from './routes/admin.reconciliation'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as MerchantApiKeysRouteImport } from './routes/merchant.api-keys'
import { Route as MerchantDevelopersRouteImport } from './routes/merchant.developers'
import { Route as MerchantReconciliationRouteImport } from './routes/merchant.reconciliation'
import { Route as MerchantSettingsRouteImport } from './routes/merchant.settings'
import { Route as MerchantWebhooksRouteImport } from './routes/merchant.webhooks'
import { Route as AdminChannelsIndexRouteImport } from './routes/admin.channels.index'
import { Route as AdminChannelsChannelIdRouteImport } from './routes/admin.channels.$channelId'
import { Route as AdminMerchantsIndexRouteImport } from './routes/admin.merchants.index'
import { Route as AdminMerchantsMerchantIdRouteImport } from './routes/admin.merchants.$merchantId'
import { Route as AdminMerchantsNewRouteImport } from './routes/admin.merchants.new'
import { Route as AdminTransactionsIndexRouteImport } from './routes/admin.transactions.index'
import { Route as AdminTransactionsTransactionIdRouteImport } from './routes/admin.transactions.$transactionId'
import { Route as MerchantChannelsIndexRouteImport } from './routes/merchant.channels.index'
import { Route as MerchantChannelsChannelIdRouteImport } from './routes/merchant.channels.$channelId'
import { Route as MerchantChannelsNewRouteImport } from './routes/merchant.channels.new'
import { Route as MerchantTransactionsIndexRouteImport } from './routes/merchant.transactions.index'
import { Route as MerchantTransactionsTransactionIdRouteImport } from './routes/merchant.transactions.$transactionId'
import { Route as AdminMerchantsMerchantIdChannelsNewRouteImport } from './routes/admin.merchants.$merchantId.channels.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/admin/api-keys',
  path: '/admin/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevelopersRoute = AdminDevelopersRouteImport.update({
  id: '/admin/developers',
  path: '/admin/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReconciliationRoute = AdminReconciliationRouteImport.update({
  id: '/admin/reconciliation',
  path: '/admin/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/admin/webhooks',
  path: '/admin/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/merchant/',
  path: '/merchant/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantApiKeysRoute = MerchantApiKeysRouteImport.update({
  id: '/merchant/api-keys',
  path: '/merchant/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantDevelopersRoute = MerchantDevelopersRouteImport.update({
  id: '/merchant/developers',
  path: '/merchant/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantReconciliationRoute = MerchantReconciliationRouteImport.update({
  id: '/merchant/reconciliation',
  path: '/merchant/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/merchant/settings',
  path: '/merchant/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantWebhooksRoute = MerchantWebhooksRouteImport.update({
  id: '/merchant/webhooks',
  path: '/merchant/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChannelsIndexRoute = AdminChannelsIndexRouteImport.update({
  id: '/admin/channels/',
  path: '/admin/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChannelsChannelIdRoute = AdminChannelsChannelIdRouteImport.update({
  id: '/admin/channels/$channelId',
  path: '/admin/channels/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantsIndexRoute = AdminMerchantsIndexRouteImport.update({
  id: '/admin/merchants/',
  path: '/admin/merchants/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantsMerchantIdRoute =
  AdminMerchantsMerchantIdRouteImport.update({
    id: '/admin/merchants/$merchantId',
    path: '/admin/merchants/$merchantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMerchantsNewRoute = AdminMerchantsNewRouteImport.update({
  id: '/admin/merchants/new',
  path: '/admin/merchants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsIndexRoute = AdminTransactionsIndexRouteImport.update({
  id: '/admin/transactions/',
  path: '/admin/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsTransactionIdRoute =
  AdminTransactionsTransactionIdRouteImport.update({
    id: '/admin/transactions/$transactionId',
    path: '/admin/transactions/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MerchantChannelsIndexRoute = MerchantChannelsIndexRouteImport.update({
  id: '/merchant/channels/',
  path: '/merchant/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantChannelsChannelIdRoute =
  MerchantChannelsChannelIdRouteImport.update({
    id: '/merchant/channels/$channelId',
    path: '/merchant/channels/$channelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MerchantChannelsNewRoute = MerchantChannelsNewRouteImport.update({
  id: '/merchant/channels/new',
  path: '/merchant/channels/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantTransactionsIndexRoute =
  MerchantTransactionsIndexRouteImport.update({
    id: '/merchant/transactions/',
    path: '/merchant/transactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MerchantTransactionsTransactionIdRoute =
  MerchantTransactionsTransactionIdRouteImport.update({
    id: '/merchant/transactions/$transactionId',
    path: '/merchant/transactions/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMerchantsMerchantIdChannelsNewRoute =
  AdminMerchantsMerchantIdChannelsNewRouteImport.update({
    id: '/channels/new',
    path: '/channels/new',
    getParentRoute: () => AdminMerchantsMerchantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/developers': typeof MerchantDevelopersRoute
  '/merchant/reconciliation': typeof MerchantReconciliationRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/merchant/webhooks': typeof MerchantWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/channels/$channelId': typeof AdminChannelsChannelIdRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRouteWithChildren
  '/admin/merchants/new': typeof AdminMerchantsNewRoute
  '/admin/transactions/$transactionId': typeof AdminTransactionsTransactionIdRoute
  '/merchant/channels/$channelId': typeof MerchantChannelsChannelIdRoute
  '/merchant/channels/new': typeof MerchantChannelsNewRoute
  '/merchant/transactions/$transactionId': typeof MerchantTransactionsTransactionIdRoute
  '/admin/channels/': typeof AdminChannelsIndexRoute
  '/admin/merchants/': typeof AdminMerchantsIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/merchant/channels/': typeof MerchantChannelsIndexRoute
  '/merchant/transactions/': typeof MerchantTransactionsIndexRoute
  '/admin/merchants/$merchantId/channels/new': typeof AdminMerchantsMerchantIdChannelsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/developers': typeof MerchantDevelopersRoute
  '/merchant/reconciliation': typeof MerchantReconciliationRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/merchant/webhooks': typeof MerchantWebhooksRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/admin/channels/$channelId': typeof AdminChannelsChannelIdRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRouteWithChildren
  '/admin/merchants/new': typeof AdminMerchantsNewRoute
  '/admin/transactions/$transactionId': typeof AdminTransactionsTransactionIdRoute
  '/merchant/channels/$channelId': typeof MerchantChannelsChannelIdRoute
  '/merchant/channels/new': typeof MerchantChannelsNewRoute
  '/merchant/transactions/$transactionId': typeof MerchantTransactionsTransactionIdRoute
  '/admin/channels': typeof AdminChannelsIndexRoute
  '/admin/merchants': typeof AdminMerchantsIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
  '/merchant/channels': typeof MerchantChannelsIndexRoute
  '/merchant/transactions': typeof MerchantTransactionsIndexRoute
  '/admin/merchants/$merchantId/channels/new': typeof AdminMerchantsMerchantIdChannelsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/developers': typeof MerchantDevelopersRoute
  '/merchant/reconciliation': typeof MerchantReconciliationRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/merchant/webhooks': typeof MerchantWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/channels/$channelId': typeof AdminChannelsChannelIdRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRouteWithChildren
  '/admin/merchants/new': typeof AdminMerchantsNewRoute
  '/admin/transactions/$transactionId': typeof AdminTransactionsTransactionIdRoute
  '/merchant/channels/$channelId': typeof MerchantChannelsChannelIdRoute
  '/merchant/channels/new': typeof MerchantChannelsNewRoute
  '/merchant/transactions/$transactionId': typeof MerchantTransactionsTransactionIdRoute
  '/admin/channels/': typeof AdminChannelsIndexRoute
  '/admin/merchants/': typeof AdminMerchantsIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/merchant/channels/': typeof MerchantChannelsIndexRoute
  '/merchant/transactions/': typeof MerchantTransactionsIndexRoute
  '/admin/merchants/$merchantId/channels/new': typeof AdminMerchantsMerchantIdChannelsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/admin/api-keys'
    | '/admin/developers'
    | '/admin/reconciliation'
    | '/admin/settings'
    | '/admin/webhooks'
    | '/merchant/api-keys'
    | '/merchant/developers'
    | '/merchant/reconciliation'
    | '/merchant/settings'
    | '/merchant/webhooks'
    | '/admin/'
    | '/merchant/'
    | '/admin/channels/$channelId'
    | '/admin/merchants/$merchantId'
    | '/admin/merchants/new'
    | '/admin/transactions/$transactionId'
    | '/merchant/channels/$channelId'
    | '/merchant/channels/new'
    | '/merchant/transactions/$transactionId'
    | '/admin/channels/'
    | '/admin/merchants/'
    | '/admin/transactions/'
    | '/merchant/channels/'
    | '/merchant/transactions/'
    | '/admin/merchants/$merchantId/channels/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/admin/api-keys'
    | '/admin/developers'
    | '/admin/reconciliation'
    | '/admin/settings'
    | '/admin/webhooks'
    | '/merchant/api-keys'
    | '/merchant/developers'
    | '/merchant/reconciliation'
    | '/merchant/settings'
    | '/merchant/webhooks'
    | '/admin'
    | '/merchant'
    | '/admin/channels/$channelId'
    | '/admin/merchants/$merchantId'
    | '/admin/merchants/new'
    | '/admin/transactions/$transactionId'
    | '/merchant/channels/$channelId'
    | '/merchant/channels/new'
    | '/merchant/transactions/$transactionId'
    | '/admin/channels'
    | '/admin/merchants'
    | '/admin/transactions'
    | '/merchant/channels'
    | '/merchant/transactions'
    | '/admin/merchants/$merchantId/channels/new'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/admin/api-keys'
    | '/admin/developers'
    | '/admin/reconciliation'
    | '/admin/settings'
    | '/admin/webhooks'
    | '/merchant/api-keys'
    | '/merchant/developers'
    | '/merchant/reconciliation'
    | '/merchant/settings'
    | '/merchant/webhooks'
    | '/admin/'
    | '/merchant/'
    | '/admin/channels/$channelId'
    | '/admin/merchants/$merchantId'
    | '/admin/merchants/new'
    | '/admin/transactions/$transactionId'
    | '/merchant/channels/$channelId'
    | '/merchant/channels/new'
    | '/merchant/transactions/$transactionId'
    | '/admin/channels/'
    | '/admin/merchants/'
    | '/admin/transactions/'
    | '/merchant/channels/'
    | '/merchant/transactions/'
    | '/admin/merchants/$merchantId/channels/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminDevelopersRoute: typeof AdminDevelopersRoute
  AdminReconciliationRoute: typeof AdminReconciliationRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  MerchantApiKeysRoute: typeof MerchantApiKeysRoute
  MerchantDevelopersRoute: typeof MerchantDevelopersRoute
  MerchantReconciliationRoute: typeof MerchantReconciliationRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  MerchantWebhooksRoute: typeof MerchantWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  AdminChannelsChannelIdRoute: typeof AdminChannelsChannelIdRoute
  AdminMerchantsMerchantIdRoute: typeof AdminMerchantsMerchantIdRouteWithChildren
  AdminMerchantsNewRoute: typeof AdminMerchantsNewRoute
  AdminTransactionsTransactionIdRoute: typeof AdminTransactionsTransactionIdRoute
  MerchantChannelsChannelIdRoute: typeof MerchantChannelsChannelIdRoute
  MerchantChannelsNewRoute: typeof MerchantChannelsNewRoute
  MerchantTransactionsTransactionIdRoute: typeof MerchantTransactionsTransactionIdRoute
  AdminChannelsIndexRoute: typeof AdminChannelsIndexRoute
  AdminMerchantsIndexRoute: typeof AdminMerchantsIndexRoute
  AdminTransactionsIndexRoute: typeof AdminTransactionsIndexRoute
  MerchantChannelsIndexRoute: typeof MerchantChannelsIndexRoute
  MerchantTransactionsIndexRoute: typeof MerchantTransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/developers': {
      id: '/admin/developers'
      path: '/admin/developers'
      fullPath: '/admin/developers'
      preLoaderRoute: typeof AdminDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reconciliation': {
      id: '/admin/reconciliation'
      path: '/admin/reconciliation'
      fullPath: '/admin/reconciliation'
      preLoaderRoute: typeof AdminReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/admin/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/api-keys': {
      id: '/merchant/api-keys'
      path: '/merchant/api-keys'
      fullPath: '/merchant/api-keys'
      preLoaderRoute: typeof MerchantApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/developers': {
      id: '/merchant/developers'
      path: '/merchant/developers'
      fullPath: '/merchant/developers'
      preLoaderRoute: typeof MerchantDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/reconciliation': {
      id: '/merchant/reconciliation'
      path: '/merchant/reconciliation'
      fullPath: '/merchant/reconciliation'
      preLoaderRoute: typeof MerchantReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/merchant/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/webhooks': {
      id: '/merchant/webhooks'
      path: '/merchant/webhooks'
      fullPath: '/merchant/webhooks'
      preLoaderRoute: typeof MerchantWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/channels/': {
      id: '/admin/channels/'
      path: '/admin/channels'
      fullPath: '/admin/channels/'
      preLoaderRoute: typeof AdminChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/channels/$channelId': {
      id: '/admin/channels/$channelId'
      path: '/admin/channels/$channelId'
      fullPath: '/admin/channels/$channelId'
      preLoaderRoute: typeof AdminChannelsChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants/': {
      id: '/admin/merchants/'
      path: '/admin/merchants'
      fullPath: '/admin/merchants/'
      preLoaderRoute: typeof AdminMerchantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants/$merchantId': {
      id: '/admin/merchants/$merchantId'
      path: '/admin/merchants/$merchantId'
      fullPath: '/admin/merchants/$merchantId'
      preLoaderRoute: typeof AdminMerchantsMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants/new': {
      id: '/admin/merchants/new'
      path: '/admin/merchants/new'
      fullPath: '/admin/merchants/new'
      preLoaderRoute: typeof AdminMerchantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions/': {
      id: '/admin/transactions/'
      path: '/admin/transactions'
      fullPath: '/admin/transactions/'
      preLoaderRoute: typeof AdminTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions/$transactionId': {
      id: '/admin/transactions/$transactionId'
      path: '/admin/transactions/$transactionId'
      fullPath: '/admin/transactions/$transactionId'
      preLoaderRoute: typeof AdminTransactionsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/channels/': {
      id: '/merchant/channels/'
      path: '/merchant/channels'
      fullPath: '/merchant/channels/'
      preLoaderRoute: typeof MerchantChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/channels/$channelId': {
      id: '/merchant/channels/$channelId'
      path: '/merchant/channels/$channelId'
      fullPath: '/merchant/channels/$channelId'
      preLoaderRoute: typeof MerchantChannelsChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/channels/new': {
      id: '/merchant/channels/new'
      path: '/merchant/channels/new'
      fullPath: '/merchant/channels/new'
      preLoaderRoute: typeof MerchantChannelsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/transactions/': {
      id: '/merchant/transactions/'
      path: '/merchant/transactions'
      fullPath: '/merchant/transactions/'
      preLoaderRoute: typeof MerchantTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/transactions/$transactionId': {
      id: '/merchant/transactions/$transactionId'
      path: '/merchant/transactions/$transactionId'
      fullPath: '/merchant/transactions/$transactionId'
      preLoaderRoute: typeof MerchantTransactionsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants/$merchantId/channels/new': {
      id: '/admin/merchants/$merchantId/channels/new'
      path: '/channels/new'
      fullPath: '/admin/merchants/$merchantId/channels/new'
      preLoaderRoute: typeof AdminMerchantsMerchantIdChannelsNewRouteImport
      parentRoute: typeof AdminMerchantsMerchantIdRoute
    }
  }
}

interface AdminMerchantsMerchantIdRouteChildren {
  AdminMerchantsMerchantIdChannelsNewRoute: typeof AdminMerchantsMerchantIdChannelsNewRoute
}

const AdminMerchantsMerchantIdRouteChildren: AdminMerchantsMerchantIdRouteChildren =
  {
    AdminMerchantsMerchantIdChannelsNewRoute:
      AdminMerchantsMerchantIdChannelsNewRoute,
  }

const AdminMerchantsMerchantIdRouteWithChildren =
  AdminMerchantsMerchantIdRoute._addFileChildren(
    AdminMerchantsMerchantIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminDevelopersRoute: AdminDevelopersRoute,
  AdminReconciliationRoute: AdminReconciliationRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  MerchantApiKeysRoute: MerchantApiKeysRoute,
  MerchantDevelopersRoute: MerchantDevelopersRoute,
  MerchantReconciliationRoute: MerchantReconciliationRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  MerchantWebhooksRoute: MerchantWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  AdminChannelsChannelIdRoute: AdminChannelsChannelIdRoute,
  AdminMerchantsMerchantIdRoute: AdminMerchantsMerchantIdRouteWithChildren,
  AdminMerchantsNewRoute: AdminMerchantsNewRoute,
  AdminTransactionsTransactionIdRoute: AdminTransactionsTransactionIdRoute,
  MerchantChannelsChannelIdRoute: MerchantChannelsChannelIdRoute,
  MerchantChannelsNewRoute: MerchantChannelsNewRoute,
  MerchantTransactionsTransactionIdRoute:
    MerchantTransactionsTransactionIdRoute,
  AdminChannelsIndexRoute: AdminChannelsIndexRoute,
  AdminMerchantsIndexRoute: AdminMerchantsIndexRoute,
  AdminTransactionsIndexRoute: AdminTransactionsIndexRoute,
  MerchantChannelsIndexRoute: MerchantChannelsIndexRoute,
  MerchantTransactionsIndexRoute: MerchantTransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
